//LOGIN
export const LOGIN = 'LOGIN_USER'; 
export const LOGOUT = 'LOGOUT_USER'; 

//REGISTER
export const REGISTER = 'REGISTER_USER'; 

//WORKOUTS
export const POST_WORKOUT = 'POST_WORKOUT';
export const GET_WORKOUTS = 'GET_WORKOUTS';
export const ADD_WORKOUT = 'ADD_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const GET_WORKOUT_TYPES = 'GET_WORKOUT_TYPES';

//REQUESTS
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const RECEIVING_REQUEST = 'RECEIVING_REQUEST';

//HANDLING ERRORS
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const AUTH_ERROR = 'AUTHENTICATION_ERROR';
export const ROUTE_CHANGE = 'ROUTE_CHANGE'; 